/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32_103.h"
#include "stm32_GPIO.h"
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void delay(uint32_t time)
{
    for (uint32_t i = 0; i < time * 1000; i++)
    {
        __asm("NOP");
    }
}

int main(void)
{
  GPIO_Config_t led_config = {
      .GPIO_Pin_Number = GPIO_PIN_NO_13,
      .GPIO_Pin_Mode = GPIO_MODE_OUTPUT,
      .GPIO_Type = GPIO_CNF_ANALOG,  // CNF = 00
      .GPIO_Pin_Speed = GPIO_SPEED_LOW  // MODE = 10
  };
  
  GPIO_Handle_t led = {
      .pGPIOx = GPIOC,
      .pGPIO_Config = &led_config
  };
  
  GPIO_Init(&led);

    /* Loop forever */
  while (1)
  {
    GPIO_ToggleOutputPin(GPIOC, GPIO_PIN_NO_13);
    delay(100);
  }
  
}

void EXTI0_IRQHandler(){
  GPIO_IRQHandling(0);
}
